
--Test 1 2 

INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (1,123456,'CodRR','Oui',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (2,321456,'RRCod','OuiLiee',87)

--Test 3 4 
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (3,456456,'CoRR2','Oui',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (4,654456,'RRCo2','OuiLiee',87)


--Test 5 6 
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (5,789456,'CoRR3','Oui',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (6,987456,'RRCo3','OuiLiee',87)