
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (1491, 381194, 'FRDCK', 'CHARS',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (6646, 763029, 'FRVLA', 'VALENCE TGV RHONE-ALPES SUD',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (25, 444877, 'FRACK', 'CHERBOURG',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (1518, 381624, 'FRDDM', 'BREVAL',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (5533, 384008, 'FRPSL', 'PARIS ST LAZARE',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) values (5544, 411207, 'FROIL', 'OISSEL',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) values (5645, 444315, 'FRSQY', 'SERQUIGNY',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) values (5788, 411017, 'FRURD', 'ROUEN RIVE DROITE',87);
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) values (5798, 381244, 'FRDCP', 'GISORS EMBRANCHEMENT',87);