-- Test 1 2
INSERT [dbo].[ADM_GARE_ICTER] ([GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (1,2)

--Test 3 4
INSERT [dbo].[ADM_GARE_ICTER] ([GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (3,4)

--Test 5 6
INSERT [dbo].[ADM_GARE_ICTER] ([GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (5,6)
