
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (1,123456,'CodRR','Oui',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (2,654321,'RRCod','OuiLiee',87)