
--Test 1 2 3

INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (1,123456,'CodRR','Oui',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (2,321456,'RRCod','OuiLiee',87)


--Test 4 
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (3,456456,'CodR','OuiLiee',87)
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (4,654456,'CRod','OuiLiee',87)

--Test 5 
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (5,111456,'CRod','OuiLiee',87)

--Test 6
INSERT [dbo].[ADM_GARE] ([ADM_GARE_ID], [CODE_UIC], [CODE_RR], [INTITULE], [CODE_RESEAU_UIC]) VALUES (6,222456,'CRod','OuiLiee',87)
