-- Code bare numéro 35
INSERT [dbo].[LDV_DOSSIER_VOYAGE] ([ID],[LISTE_ID],[DATE_CREATION],[DATE_MODIFICATION],[DATE_DEBUT_VALID],[DATE_FIN_VALID],[IND_ACTIF]) VALUES (35, 'DV0035', '2019-29-04','2019-29-04', '2018-09-11','2018-09-11', 1)
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (35, 35, 'FRPSL')
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (35, 35, 'ID_HOUSTON')
INSERT [dbo].[LDV_TICKET] ([ID],[COURSE_ID],[TCN],[ORDER_ID],[SERVICELTEMLD],[PNR],[STATUS],[TICKET_KIND],[TICKET_CODE],[FARE_CODE],[CODE_DT]) VALUES (35,35,'617339741','orderId','serviceTemld', 'PNR','ACTIVE','kind_ticket','code ticket','fare code','code dt')
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (35, 35, '384008', '')
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (35, 35, 'nbTrain', '2018-09-11', '2018-09-11', 'FRACK', 'FRPSL', 'carrier code')
INSERT [dbo].[LDV_TICKET_MARK_INFORMATION] ([ID],[SEGMENT_ID],[UIC],[MARK_DEVICE_ID],[MARK_DEVICE_TYPE],[AGENT_CP],[TICKET_MARK_DATE],[MARK_STATION],[TICKET_MARK_TYPE],[TRAIN_NUMBER_ORIGINAL],[DEPARTURE_TIME_ORIGINAL],[TRAIN_NUMBER_MARKED],[DEPARTURE_TIME_MARKED]) VALUES (35, 35, '384008','deviceId', 'deviceType', 'agent cp', '2018-09-11', 'station', 'PENDING_NONE', 'nbTrain', '2018-09-11', 'nbTrain', '2018-09-11')
