--Test 1 2
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (1, 1, 'RRCode')

--Test 3 4
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (2, 1, 'CoRR2')

--Test 5 
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (3, 2, 'CoRR3')
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (4, 3, 'CoRR3')

--Test 6
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (5, 4, 'CoRR4')
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (6, 5, 'CoRR4')
