--Test 1 2 
INSERT [dbo].[LDV_TICKET_MARK_INFORMATION] ([ID],[SEGMENT_ID],[UIC],[MARK_DEVICE_ID],[MARK_DEVICE_TYPE],[AGENT_CP],[TICKET_MARK_DATE],[MARK_STATION],[TICKET_MARK_TYPE],[TRAIN_NUMBER_ORIGINAL],[DEPARTURE_TIME_ORIGINAL],[TRAIN_NUMBER_MARKED],[DEPARTURE_TIME_MARKED]) VALUES (1, 1, 'UIC','deviceId', 'deviceType', 'agent cp', GETDATE(), 'station', 'PENDING_NONE', 'nbTrain', GETDATE(), 'nbTrain', GETDATE())

--Test 3
INSERT [dbo].[LDV_TICKET_MARK_INFORMATION] ([ID],[SEGMENT_ID],[UIC],[MARK_DEVICE_ID],[MARK_DEVICE_TYPE],[AGENT_CP],[TICKET_MARK_DATE],[MARK_STATION],[TICKET_MARK_TYPE],[TRAIN_NUMBER_ORIGINAL],[DEPARTURE_TIME_ORIGINAL],[TRAIN_NUMBER_MARKED],[DEPARTURE_TIME_MARKED]) VALUES (2, 2, 'UIC','deviceId', 'deviceType', 'agent cp', GETDATE(), 'station', 'PENDING_NONE', 'nbTrain', GETDATE(), 'nbTrain', GETDATE())

--Test 4
INSERT [dbo].[LDV_TICKET_MARK_INFORMATION] ([ID],[SEGMENT_ID],[UIC],[MARK_DEVICE_ID],[MARK_DEVICE_TYPE],[AGENT_CP],[TICKET_MARK_DATE],[MARK_STATION],[TICKET_MARK_TYPE],[TRAIN_NUMBER_ORIGINAL],[DEPARTURE_TIME_ORIGINAL],[TRAIN_NUMBER_MARKED],[DEPARTURE_TIME_MARKED]) VALUES (3, 3, 'UIC','deviceId', 'deviceType', 'agent cp', GETDATE(), 'station', 'STAMPED', 'nbTrain', GETDATE(), 'nbTrain', GETDATE())
INSERT [dbo].[LDV_TICKET_MARK_INFORMATION] ([ID],[SEGMENT_ID],[UIC],[MARK_DEVICE_ID],[MARK_DEVICE_TYPE],[AGENT_CP],[TICKET_MARK_DATE],[MARK_STATION],[TICKET_MARK_TYPE],[TRAIN_NUMBER_ORIGINAL],[DEPARTURE_TIME_ORIGINAL],[TRAIN_NUMBER_MARKED],[DEPARTURE_TIME_MARKED]) VALUES (4, 4, 'UIC','deviceId', 'deviceType', 'agent cp', GETDATE(), 'station', 'STAMPED', 'nbTrain', GETDATE(), 'nbTrain', GETDATE())
