-- Test 1, 2 
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (1, 1, 'UIC', 'LOYALTY_NUMBER1')

-- Test 3, 4
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (2, 2, 'UIC', 'LOYALTY_NUMBER1')


-- Test 5
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (3, 3, 'UIC', 'LOYALTY_NUMBER1')
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (4, 4, 'UIC', 'LOYALTY_NUMBER1')

-- Test 6
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (5, 5, 'UIC', 'LOYALTY_NUMBER1')
INSERT [dbo].[LDV_PASSAGER] ([ID],[TICKET_ID],[UIC],[LOYALTY_NUMBER]) VALUES (6, 6, 'UIC', 'LOYALTY_NUMBER1')
