--Test 1 2
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (1, 1, 'CodRR')

--Test 3
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (2, 2, 'RRCod')

--Test 4
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (3, 2, 'CodR')
INSERT [dbo].[LDV_GARE] ([ID],[LISTE_DOSSIER_VOYAGE_ID],[RR_CODE]) VALUES (4, 2, 'CRod')
