-- Test 1 2 
INSERT [dbo].[LDV_DOSSIER_VOYAGE] ([ID],[LISTE_ID],[DATE_CREATION],[DATE_MODIFICATION],[DATE_DEBUT_VALID],[DATE_FIN_VALID],[IND_ACTIF]) VALUES (1, 'List', GETDATE(), GETDATE(), GETDATE(),DATEADD(day, 1, GETDATE()), 1)

-- Test 3 
INSERT [dbo].[LDV_DOSSIER_VOYAGE] ([ID],[LISTE_ID],[DATE_CREATION],[DATE_MODIFICATION],[DATE_DEBUT_VALID],[DATE_FIN_VALID],[IND_ACTIF]) VALUES (2, 'List2', GETDATE(), GETDATE(), GETDATE(),DATEADD(day, 1, GETDATE()), 1)


-- Test 4
INSERT [dbo].[LDV_DOSSIER_VOYAGE] ([ID],[LISTE_ID],[DATE_CREATION],[DATE_MODIFICATION],[DATE_DEBUT_VALID],[DATE_FIN_VALID],[IND_ACTIF]) VALUES (3, 'List3', GETDATE(), GETDATE(), GETDATE(),DATEADD(day, 1, GETDATE()), 1)



-- Test 5
INSERT [dbo].[LDV_DOSSIER_VOYAGE] ([ID],[LISTE_ID],[DATE_CREATION],[DATE_MODIFICATION],[DATE_DEBUT_VALID],[DATE_FIN_VALID],[IND_ACTIF]) VALUES (4, 'List4', GETDATE(), GETDATE(), GETDATE(),DATEADD(day, 1, GETDATE()), 1)
