--Test 1 2
--Test 1 2
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (1, 1, 'nbTrain', GETDATE(), GETDATE(), 'Nolie', 'Nolie', 'carrier code')

-- Test 3 4
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (2, 2, 'nbTrain', GETDATE(), GETDATE(), 'CoRR2', 'CoRR2', 'carrier code')

--Test 5
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (3,3, 'nbTrain', GETDATE(), GETDATE(), 'CoRR3', 'CoRR3', 'carrier code')
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (4,4, 'nbTrain', GETDATE(), GETDATE(), 'CoRR3', 'CoRR3', 'carrier code')

--Test6
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (5, 5, 'nbTrain', GETDATE(), GETDATE(), 'CoRR3', 'CoRR3', 'carrier code')
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (6, 6, 'nbTrain', GETDATE(), GETDATE(), 'CoRR3', 'CoRR3', 'carrier code')
