-- Test 1 2
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (1, 1, 'ID_HOUSTON')

--Test 3 4
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (2, 2, 'ID_HOUSTON')

--Test 5 
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (3, 3, 'ID_HOUSTON')
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (4, 4, 'ID_HOUSTON')

--Test 6
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (5, 5, 'ID_HOUSTON')
INSERT [dbo].[LDV_COURSE] ([ID],[GARE_ID],[ID_HOUSTON]) VALUES (6, 6, 'ID_HOUSTON')
