--Test 1 2
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (1, 1, 'nbTrain', GETDATE(), GETDATE(), 'CodRR', 'RRCod', 'carrier code')

--Test 3 
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (2, 2, 'nbTrain', GETDATE(), GETDATE(), 'Cod', 'Cod', 'carrier code')

--Test 4
--Origine et Destination contenue dans listCodeRRGareLiee 
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (3, 3, 'nbTrain', GETDATE(), GETDATE(), 'CodR', 'RRCod', 'carrier code')
INSERT [dbo].[LDV_SEGMENT] ([ID],[TICKET_ID],[TRAIN_NUMBER],[DEPARTURE_TIME],[ARRIVAL_TIME],[ORIGIN],[DESTINATION],[CARRIER_CODE]) VALUES (4, 4, 'nbTrain', GETDATE(), GETDATE(), 'RRCod', 'CRod', 'carrier code')
