-- Test 1
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (1,1,1,2)

--Test 2 
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (2,3,1,2)

--Test 3 
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (3,5,1,2)

--Test 4
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (4,7,1,2)

--Test 5
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (5,9,1,2)

--Test 6
INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (6,11,1,2)