

INSERT [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID], [GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (1, 150, 1, 1491);
INSERT [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID], [GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (2, 150, 1, 1518);
INSERT [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID], [GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (3, 150, 1, 6646);
INSERT [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID], [GARE_ICTER_ID], [ADM_GARE_ID]) VALUES (4, 150, 1, 25);