--Test 1 
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (2,'v1',2,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 2
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (3,'v2',4,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 3
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (4,'v2',6,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 4
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (5,'v2',8,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 5
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (6,'v2',10,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 6
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (7,'v2',12,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 7

INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (8,'v2',14,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')
