--AcceptCarteFidelEMB True 
-- Test 1
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (1,NULL,NULL,NULL,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL)

--AcceptCarteFidelEMB False
-- Test 2
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (3,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL)

--AcceptCarteFidelEMB True 
-- Test 3
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (5,NULL,NULL,NULL,NULL,0,0,1,NULL,NULL,NULL,NULL,NULL)

--AcceptCarteFidelEMB False
-- Test 4
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (7,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL)

-- Test 4
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (9,NULL,NULL,NULL,NULL,NULL,0,0,0,1,NULL,NULL,NULL)

-- Test 4
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (11,NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL)