--ICTPGEN
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,140)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,141)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,142)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,143)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,144)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,145)

--TITRE
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,135)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,135)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,135)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,135)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,135)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,135)

--TARIF
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,136)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,136)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,136)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,136)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,136)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,136)


--Gares Liees
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,150)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,150)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,150)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,150)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,150)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,150)


