
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (2, 136, 'AT')
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (3, 136, 'FA')
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (4, 136, 'FF')
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (5, 136, 'FQ')
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (6, 136, 'PT')
INSERT [dbo].[PAR_TARIF] ([TARIF_ID], [JEU_ID], [CODE_TARIF]) VALUES (7, 136, 'PG')
