--Test 1 
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (1,11)

-- Test 2
--N'accepete pas EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,12)





-- Test 3
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,11)



-- Test 4
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,11)

INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,11)


-- Test 5
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,11)

-- Test 6
--N'accepete pas EMB et DEB
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (7,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (7,2)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (7,12)
