INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (1,1,1,1)


INSERT INTO [dbo].[PAR_GARE_LIEE] ([GARE_LIEE_ID], [JEU_ID],[GARE_ICTER_ID],[ADM_GARE_ID]) VALUES (2,1,2,2)

