
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (1, 135, 'NOVOD')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (2, 135, 'DBROD')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (3, 135, 'PVMOD')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (4, 135, 'T1')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (5, 135, 'DV')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (6, 135, 'BC')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (7, 135, 'BS')
INSERT [dbo].[PAR_TITRE] ([TITRE_ID], [JEU_ID], [CODE_TITRE]) VALUES (8, 135, 'CV')
