
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (1,NULL,NULL,NULL,1,0,0,1,NULL,NULL,NULL,NULL,NULL)

INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (2,NULL,NULL,NULL,0,0,0,1,NULL,NULL,NULL,NULL,NULL)
