--Test 1 
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (1,'TestNom','TestIndGrpExist',87123,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist')

--Test 2
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (2,'TestNom','TestIndGrpExist',87123,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist2')


--Test 3
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (3,'TestNom','TestIndGrpExist',87321,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist3')


--Test 4
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (4,'TestNom','TestIndGrpExist',87456,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist4')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (5,'TestNom','TestIndGrpExist',87654,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist5')

--Test 5
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (6,'TestNom','TestIndGrpExist',111,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist6')

--Test 6
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (7,'TestNom','TestIndGrpExist',222,GETDATE(), DATEADD(day, 1,GETDATE()), 'TestExist7')
