--Test 1 
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,1)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (2,2)

--Test 2
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,3)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (3,4)

--Test 3
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,5)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (4,6)


--Test 4
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,7)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (5,8)


--Test 5
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,9)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (6,10)


--Test 6
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (7,11)
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (7,12)


--Test 7
INSERT INTO [dbo].[PAR_ASS_CONF_PARAM] ([CONFIGURATION_ID], [JEU_ID] ) VALUES (8,13)
