
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (4, 2, '21')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (5, 2, '23')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (6, 3, '22')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (7, 4, '21')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (8, 4, '23')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (9, 5, '22')
INSERT [dbo].[PAR_TARIF_CAR] ([TARIF_CAR_ID], [TARIF_ID], [CARACTERISTIQUE]) VALUES (10,6, '22')