--Test 1
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (2,1,1,1,1,1,1,1,1,1,1,1,1)

--Test 2 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (4,1,1,1,1,1,0,0,0,0,1,1,1)

--Test 3
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (6,1,1,1,1,1,1,1,1,1,1,1,1)

--Test 4 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (8,1,1,1,1,1,0,0,0,0,1,1,1)

--Test 5 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (10,1,1,1,1,1,1,1,1,1,1,1,1)

--Test 6
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (12,1,1,1,1,1,0,0,0,0,1,1,1)

--Test 57
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID], [ACTIVATION_CB2D],[ACTIVATION_CB2DONLINE],[DUREE_ANTIPASSBACK],[ACCEPT_TITRE_TEST],[DELAI_MAX_ENT_SORT],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE],[DELAI_RETRY_CO]) VALUES (13,1,1,1,1,1,1,1,1,1,1,1,1)
