--Test 1 
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (2,'TestNom','TestIndGrpExist',87123,GETDATE(), GETDATE(), 'TestExist')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (3,'TestNom','TestIndGrpExist',87321,GETDATE(), GETDATE(), 'TestExist')

--Test 2 
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (4,'TestNom','TestIndGrpExist',87123,GETDATE(), GETDATE(), 'TestExist2')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (5,'TestNom','TestIndGrpExist',87321,GETDATE(), GETDATE(), 'TestExist2')


--Test 3 
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (6,'TestNom','TestIndGrpExist',87456,GETDATE(), GETDATE(), 'TestExist3')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (7,'TestNom','TestIndGrpExist',87654,GETDATE(), GETDATE(), 'TestExist3')

--Test 4
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (8,'TestNom','TestIndGrpExist',87456,GETDATE(), GETDATE(), 'TestExist4')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (9,'TestNom','TestIndGrpExist',87654,GETDATE(), GETDATE(), 'TestExist4')

--Test 5
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (10,'TestNom','TestIndGrpExist',87789,GETDATE(), GETDATE(), 'TestExist5')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (11,'TestNom','TestIndGrpExist',87987,GETDATE(), GETDATE(), 'TestExist5')

--Test 6
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (12,'TestNom','TestIndGrpExist',87789,GETDATE(), GETDATE(), 'TestExist6')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (13,'TestNom','TestIndGrpExist',87987,GETDATE(), GETDATE(), 'TestExist6')



--Test 7
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (14,'TestNom','TestIndGrpExist',87147,GETDATE(), GETDATE(), 'TestExist7')
INSERT INTO [dbo].[PAR_GROUPE_EQUIPEMENT] ([GRP_EQUIPEMENT_ID], [NOM], [IND_GROUPE_PILOTE], [CODE_UIC], [EDIT_USER], [EDIT_START],[IDG_NUMGROUP] ) VALUES (15,'TestNom','TestIndGrpExist',87741,GETDATE(), GETDATE(), 'TestExist7')
