
--Param 1
--minute, minute, seconde
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (140,1,1,1,1,1,1,1,240,20,600,null,null)

--Param 2 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (141,1,1,1,0,0,0,0,240,20,600,null,null)

--Param 3 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (142,1,1,1,0,0,1,1,240,20,600,null,null)

--Param 4 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (143,1,1,1,1,1,0,0,240,20,600,null,null)

--Param 5 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (144,1,0,1,1,1,1,1,240,20,600,null,null)

--Param 6 
INSERT INTO [dbo].[PAR_ICTPGEN] ([JEU_ID],[ACTIVATION_CB2D],[ACCEPT_TITRE_TEST],[ACTIVATION_CB2DONLINE],[ACCEPT_CB2D_AUTO_EMB],[ACCEPT_CARTE_FIDEL_EMB],[ACCEPT_CB2D_AUTO_DEB],[ACCEPT_CARTE_FIDEL_DEB],[DELAI_MAX_ENT_SORT],[DUREE_ANTIPASSBACK],[DELAI_RETRY_CO],[PING_PERIODE_VALONLINE],[PING_TIMEOUT_VALONLINE]) VALUES (145,1,1,1,1,1,1,1,240,20,600,null,null) --ListeDV incactive