--Test 1 
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (1,'v1',1,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 2
--N'accepete  pas EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (2,'v1',2,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 3
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (3,'v1',3,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 4
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (4,'v1',4,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (5,'v1',5,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')

--Test 5
--Accepete EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (6,'v1',6,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')


--Test 6
--N'accepete pas EMB et DEB
INSERT INTO [dbo].[PAR_CONFIGURATION] ([CONFIGURATION_ID], [VERSION], [GRP_EQUIPEMENT_ID], [EMPREINTE], [ETAT], [DATE_CHANGEMENT_ETAT], [DATE_APPLICATION_FUTURE], [COMMENTAIRE_APPLICATION] ) VALUES (7,'v1',7,'TestE','DIFSR',GETDATE(), GETDATE(),'TestCommentaire')
